MAPPING_DICT = {
    # --- SPINE & CORE ---
    'spine':            {'Adult': 'DEF-Adult_spine',            'Child': 'DEF-Child_spine',            'scale_y': 1.0, 'scale_xz': 0.0},
    'spine.001':        {'Adult': 'DEF-Adult_spine.001',        'Child': 'DEF-Child_spine.001',        'scale_y': 1.0, 'scale_xz': 0.0},
    'spine.002':        {'Adult': 'DEF-Adult_spine.002',        'Child': 'DEF-Child_spine.002',        'scale_y': 1.0, 'scale_xz': 0.0},
    'spine.003':        {'Adult': 'DEF-Adult_spine.003',        'Child': 'DEF-Child_spine.003',        'scale_y': 1.0, 'scale_xz': 0.0},
    'spine.004':        {'Adult': 'DEF-Adult_spine.004',        'Child': 'DEF-Child_spine.004',        'scale_y': 1.0, 'scale_xz': 0.0},
    'spine.005':        {'Adult': 'DEF-Adult_spine.005',        'Child': 'DEF-Child_spine.005',        'scale_y': 1.0, 'scale_xz': 0.0},
    'spine.006':        {'Adult': 'DEF-Adult_spine.006',        'Child': 'DEF-Child_spine.006',        'scale_y': 1.0, 'scale_xz': 0.0},
    'pelvis.L':         {'Adult': 'DEF-Adult_pelvis.L',         'Child': 'DEF-Child_pelvis.L',         'scale_y': 1.0, 'scale_xz': 0.0},
    'pelvis.R':         {'Adult': 'DEF-Adult_pelvis.R',         'Child': 'DEF-Child_pelvis.R',         'scale_y': 1.0, 'scale_xz': 0.0},

    # --- HEAD & FACE ---
    'face':             {'Adult': 'ORG-Adult_face',             'Child': 'ORG-Child_face',             'scale_y': 1.0, 'scale_xz': 0.0},
    'muzzle':           {'Adult': 'ORG-Adult_muzzle',           'Child': 'ORG-Child_muzzle',           'scale_y': 1.0, 'scale_xz': 0.0},
    'noz':              {'Adult': 'ORG-Adult_noz',              'Child': 'ORG-Child_noz',              'scale_y': 1.0, 'scale_xz': 0.0},
    'Eye.r':            {'Adult': 'ORG-Adult_Eye.r',            'Child': 'ORG-Child_Eye.r',            'scale_y': 1.0, 'scale_xz': 0.0},
    'Eye.l':            {'Adult': 'ORG-Adult_Eye.l',            'Child': 'ORG-Child_Eye.l',            'scale_y': 1.0, 'scale_xz': 0.0},
    'eyebrow.r':        {'Adult': 'ORG-Adult_eyebrow.r',        'Child': 'ORG-Child_eyebrow.r',        'scale_y': 1.0, 'scale_xz': 0.0},
    'eyebrow.l':        {'Adult': 'ORG-Adult_eyebrow.l',        'Child': 'ORG-Child_eyebrow.l',        'scale_y': 1.0, 'scale_xz': 0.0},
    'Ear.r':            {'Adult': 'ORG-Adult_Ear.r',            'Child': 'ORG-Child_Ear.r',            'scale_y': 1.0, 'scale_xz': 0.0},
    'Ear.001.r':        {'Adult': 'ORG-Adult_Ear.001.r',        'Child': 'ORG-Child_Ear.001.r',        'scale_y': 1.0, 'scale_xz': 0.0},
    'Ear.l':            {'Adult': 'ORG-Adult_Ear.l',            'Child': 'ORG-Child_Ear.l',            'scale_y': 1.0, 'scale_xz': 0.0},
    'Ear.001.l':        {'Adult': 'ORG-Adult_Ear.001.l',        'Child': 'ORG-Child_Ear.001.l',        'scale_y': 1.0, 'scale_xz': 0.0},
    'plays.r':          {'Adult': 'ORG-Adult_plays.r',          'Child': 'ORG-Child_plays.r',          'scale_y': 1.0, 'scale_xz': 0.0},
    'plays.l':          {'Adult': 'ORG-Adult_plays.l',          'Child': 'ORG-Child_plays.l',          'scale_y': 1.0, 'scale_xz': 0.0},
    'fix-hear.r':       {'Adult': 'ORG-Adult_fix-hear.r',       'Child': 'ORG-Child_fix-hear.r',       'scale_y': 1.0, 'scale_xz': 0.0},
    'fix-hear.l':       {'Adult': 'ORG-Adult_fix-hear.l',       'Child': 'ORG-Child_fix-hear.l',       'scale_y': 1.0, 'scale_xz': 0.0},
    'fix-play.r':       {'Adult': 'ORG-Adult_fix-play.r',       'Child': 'ORG-Child_fix-play.r',       'scale_y': 1.0, 'scale_xz': 0.0},
    'fix-play.l':       {'Adult': 'ORG-Adult_fix-play.l',       'Child': 'ORG-Child_fix-play.l',       'scale_y': 1.0, 'scale_xz': 0.0},

    # --- LEFT ARM & HAND ---
    'shoulder.L':       {'Adult': 'DEF-Adult_shoulder.L',       'Child': 'DEF-Child_shoulder.L',       'scale_y': 1.0, 'scale_xz': 0.0},
    'upper_arm.L':      {'Adult': 'DEF-Adult_upper_arm.L',      'Child': 'DEF-Child_upper_arm.L',      'scale_y': 1.0, 'scale_xz': 0.0},
    'upper_arm.L.001':  {'Adult': 'DEF-Adult_upper_arm.L.001',  'Child': 'DEF-Child_upper_arm.L.001',  'scale_y': 1.0, 'scale_xz': 0.0},
    'forearm.L':        {'Adult': 'DEF-Adult_forearm.L',        'Child': 'DEF-Child_forearm.L',        'scale_y': 1.0, 'scale_xz': 0.0},
    'forearm.L.001':    {'Adult': 'DEF-Adult_forearm.L.001',    'Child': 'DEF-Child_forearm.L.001',    'scale_y': 1.0, 'scale_xz': 0.0},
    'hand.L':           {'Adult': 'DEF-Adult_hand.L',           'Child': 'DEF-Child_hand.L',           'scale_y': 1.0, 'scale_xz': 0.0},
    'palm.01.L':        {'Adult': 'DEF-Adult_palm.01.L',        'Child': 'DEF-Child_palm.01.L',        'scale_y': 1.0, 'scale_xz': 0.0},
    'palm.02.L':        {'Adult': 'DEF-Adult_palm.01.L.001',    'Child': 'DEF-Child_palm.02.L',        'scale_y': 1.0, 'scale_xz': 0.0},
    'palm.03.L':        {'Adult': 'DEF-Adult_palm.01.L.002',    'Child': 'DEF-Child_palm.03.L',        'scale_y': 1.0, 'scale_xz': 0.0},
    'f_index.01.L':     {'Adult': 'DEF-Child_Adult_f_index.01.L', 'Child': 'DEF-Child_f_index.01.L',   'scale_y': 1.0, 'scale_xz': 0.0},
    'f_index.02.L':     {'Adult': 'DEF-Adult_f_index.02.L',     'Child': 'DEF-Child_f_index.02.L',     'scale_y': 1.0, 'scale_xz': 0.0},
    'f_index.03.L':     {'Adult': 'DEF-Adult_f_index.03.L',     'Child': 'DEF-Child_f_index.03.L',     'scale_y': 1.0, 'scale_xz': 0.0},
    'f_middle.01.L':    {'Adult': 'DEF-Adult_f_middle.01.L',    'Child': 'DEF-Child_f_middle.01.L',    'scale_y': 1.0, 'scale_xz': 0.0},
    'f_middle.02.L':    {'Adult': 'DEF-Adult_f_middle.02.L',    'Child': 'DEF-Child_f_middle.02.L',    'scale_y': 1.0, 'scale_xz': 0.0},
    'f_middle.03.L':    {'Adult': 'DEF-Adult_f_middle.03.L',    'Child': 'DEF-Child_f_middle.03.L',    'scale_y': 1.0, 'scale_xz': 0.0},
    'f_pinky.01.L':     {'Adult': 'DEF-Adult_f_index.01.L',     'Child': 'DEF-Child_f_pinky.01.L',     'scale_y': 1.0, 'scale_xz': 0.0},
    'f_pinky.02.L':     {'Adult': 'DEF-Adult_f_index.02.L.001', 'Child': 'DEF-Child_f_pinky.02.L',     'scale_y': 1.0, 'scale_xz': 0.0},
    'f_pinky.03.L':     {'Adult': 'DEF-Adult_f_index.01.L.001', 'Child': 'DEF-Child_f_pinky.03.L',     'scale_y': 1.0, 'scale_xz': 0.0},
    'thumb.01.L':       {'Adult': 'DEF-Adult_thumb.01.L',       'Child': 'DEF-Child_thumb.01.L',       'scale_y': 1.0, 'scale_xz': 0.0},
    'thumb.02.L':       {'Adult': 'DEF-Adult_thumb.02.L',       'Child': 'DEF-Child_thumb.02.L',       'scale_y': 1.0, 'scale_xz': 0.0},
    'thumb.03.L':       {'Adult': 'DEF-Adult_thumb.03.L',       'Child': 'DEF-Child_thumb.03.L',       'scale_y': 1.0, 'scale_xz': 0.0},

    # --- RIGHT ARM & HAND ---
    'shoulder.R':       {'Adult': 'DEF-Adult_shoulder.R',       'Child': 'DEF-Child_shoulder.R',       'scale_y': 1.0, 'scale_xz': 0.0},
    'upper_arm.R':      {'Adult': 'DEF-Adult_upper_arm.R',      'Child': 'DEF-Child_upper_arm.R',      'scale_y': 1.0, 'scale_xz': 0.0},
    'upper_arm.R.001':  {'Adult': 'DEF-Adult_upper_arm.R.001',  'Child': 'DEF-Child_upper_arm.R.001',  'scale_y': 1.0, 'scale_xz': 0.0},
    'forearm.R':        {'Adult': 'DEF-Adult_forearm.R',        'Child': 'DEF-Child_forearm.R',        'scale_y': 1.0, 'scale_xz': 0.0},
    'forearm.R.001':    {'Adult': 'DEF-Adult_forearm.R.001',    'Child': 'DEF-Child_forearm.R.001',    'scale_y': 1.0, 'scale_xz': 0.0},
    'hand.R':           {'Adult': 'DEF-Adult_hand.R',           'Child': 'DEF-Child_hand.R',           'scale_y': 1.0, 'scale_xz': 0.0},
    'palm.01.R':        {'Adult': 'DEF-Adult_palm.01.R',        'Child': 'DEF-Child_palm.01.R',        'scale_y': 1.0, 'scale_xz': 0.0},
    'palm.02.R':        {'Adult': 'DEF-Adult_palm.02.R',        'Child': 'DEF-Child_palm.02.R',        'scale_y': 1.0, 'scale_xz': 0.0},
    'palm.03.R':        {'Adult': 'DEF-Adult_palm.03.R',        'Child': 'DEF-Child_palm.03.R',        'scale_y': 1.0, 'scale_xz': 0.0},
    'f_index.01.R':     {'Adult': 'DEF-Adult_f_index.01.R',     'Child': 'DEF-Child_f_index.01.R',     'scale_y': 1.0, 'scale_xz': 0.0},
    'f_index.02.R':     {'Adult': 'DEF-Adult_f_index.02.R',     'Child': 'DEF-Child_f_index.02.R',     'scale_y': 1.0, 'scale_xz': 0.0},
    'f_index.03.R':     {'Adult': 'DEF-Adult_f_index.03.R',     'Child': 'DEF-Child_f_index.03.R',     'scale_y': 1.0, 'scale_xz': 0.0},
    'f_middle.01.R':    {'Adult': 'DEF-Adult_f_middle.01.R',    'Child': 'DEF-Child_f_middle.01.R',    'scale_y': 1.0, 'scale_xz': 0.0},
    'f_middle.02.R':    {'Adult': 'DEF-Adult_f_middle.02.R',    'Child': 'DEF-Child_f_middle.02.R',    'scale_y': 1.0, 'scale_xz': 0.0},
    'f_middle.03.R':    {'Adult': 'DEF-Adult_f_middle.03.R',    'Child': 'DEF-Child_f_middle.03.R',    'scale_y': 1.0, 'scale_xz': 0.0},
    'f_pinky.01.R':     {'Adult': 'DEF-Adult_f_pinky.01.R',     'Child': 'DEF-Child_f_pinky.01.R',     'scale_y': 1.0, 'scale_xz': 0.0},
    'f_pinky.02.R':     {'Adult': 'DEF-Adult_f_pinky.02.R',     'Child': 'DEF-Child_f_pinky.02.R',     'scale_y': 1.0, 'scale_xz': 0.0},
    'f_pinky.01.R.001': {'Adult': 'DEF-Adult_f_pinky.03.R',     'Child': 'DEF-Child_f_pinky.01.R.001',  'scale_y': 1.0, 'scale_xz': 0.0},
    'thumb.01.R':       {'Adult': 'DEF-Adult_thumb.01.R',       'Child': 'DEF-Child_thumb.01.R',       'scale_y': 1.0, 'scale_xz': 0.0},
    'thumb.02.R':       {'Adult': 'DEF-Adult_thumb.02.R',       'Child': 'DEF-Child_thumb.02.R',       'scale_y': 1.0, 'scale_xz': 0.0},
    'thumb.03.R':       {'Adult': 'DEF-Adult_thumb.03.R',       'Child': 'DEF-Child_thumb.03.R',       'scale_y': 1.0, 'scale_xz': 0.0},

    # --- LEGS & TAIL ---
    'Tail':             {'Adult': 'DEF-Adult_Tail',             'Child': 'DEF-Child_Tail',             'scale_y': 1.0, 'scale_xz': 0.0},
    'Tail.001':         {'Adult': 'DEF-Adult_Tail.001',         'Child': 'DEF-Child_Tail.001',         'scale_y': 1.0, 'scale_xz': 0.0},
    'Tail.002':         {'Adult': 'DEF-Adult_Tail.002',         'Child': 'DEF-Child_Tail.002',         'scale_y': 1.0, 'scale_xz': 0.0},
    'Tail.003':         {'Adult': 'DEF-Adult_Tail.003',         'Child': 'DEF-Child_Tail.003',         'scale_y': 1.0, 'scale_xz': 0.0},
    'Tail.004':         {'Adult': 'DEF-Adult_Tail.004',         'Child': 'DEF-Child_Tail.004',         'scale_y': 1.0, 'scale_xz': 0.0},
    'Tail.005':         {'Adult': 'DEF-Adult_Tail.005',         'Child': 'DEF-Child_Tail.005',         'scale_y': 1.0, 'scale_xz': 0.0},
    'thigh.L':          {'Adult': 'DEF-Adult_thigh.L',          'Child': 'DEF-Child_thigh.L',          'scale_y': 1.0, 'scale_xz': 0.0},
    'thigh.L.001':      {'Adult': 'DEF-Adult_thigh.L.001',      'Child': 'DEF-Child_thigh.L.001',      'scale_y': 1.0, 'scale_xz': 0.0},
    'shin.L':           {'Adult': 'DEF-Adult_shin.L',           'Child': 'DEF-Child_shin.L',           'scale_y': 1.0, 'scale_xz': 0.0},
    'shin.L.001':       {'Adult': 'DEF-Adult_shin.L.001',       'Child': 'DEF-Child_shin.L.001',       'scale_y': 1.0, 'scale_xz': 0.0},
    'foot.L':           {'Adult': 'DEF-Adult_foot.L',           'Child': 'DEF-Child_foot.L',           'scale_y': 1.0, 'scale_xz': 0.0},
    'toe.L':            {'Adult': 'DEF-Adult_toe.L',            'Child': 'DEF-Child_toe.L',            'scale_y': 1.0, 'scale_xz': 0.0},
    'thigh.R':          {'Adult': 'DEF-Adult_thigh.R',          'Child': 'DEF-Child_thigh.R',          'scale_y': 1.0, 'scale_xz': 0.0},
    'thigh.R.001':      {'Adult': 'DEF-Adult_thigh.R.001',      'Child': 'DEF-Child_thigh.R.001',      'scale_y': 1.0, 'scale_xz': 0.0},
    'shin.R':           {'Adult': 'DEF-Adult_shin.R',           'Child': 'DEF-Child_shin.R',           'scale_y': 1.0, 'scale_xz': 0.0},
    'shin.R.001':       {'Adult': 'DEF-Adult_shin.R.001',       'Child': 'DEF-Child_shin.R.001',       'scale_y': 1.0, 'scale_xz': 0.0},
    'foot.R':           {'Adult': 'DEF-Adult_foot.R',           'Child': 'DEF-Child_foot.R',           'scale_y': 1.0, 'scale_xz': 0.0},
    'toe.R':            {'Adult': 'DEF-Adult_toe.R',            'Child': 'DEF-Child_toe.R',            'scale_y': 1.0, 'scale_xz': 0.0},
}
